-- supabase/migrations/20251110000003_add_leveling_system.sql

-- Criar a tabela de levels
CREATE TABLE public.levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    name_jp TEXT NOT NULL,
    min_xp INT NOT NULL
);

-- Inserir os levels
INSERT INTO public.levels (name, name_jp, min_xp) VALUES
('Initiate', '新入り', 0),
('Adept', '熟練者', 10),
('Veteran', 'ベテラン', 30),
('Master', 'マスター', 60),
('Legend', '伝説', 100);

-- Adicionar as colunas de level à tabela de perfis
ALTER TABLE public.profiles
ADD COLUMN level_name TEXT DEFAULT 'Initiate',
ADD COLUMN level_name_jp TEXT DEFAULT '新入り';

-- Função para atualizar o level do usuário
CREATE OR REPLACE FUNCTION public.update_user_level()
RETURNS TRIGGER AS $$
DECLARE
    new_level RECORD;
BEGIN
    SELECT * INTO new_level
    FROM public.levels
    WHERE NEW.experience >= min_xp
    ORDER BY min_xp DESC
    LIMIT 1;

    IF new_level IS NOT NULL THEN
        NEW.level := new_level.id;
        NEW.level_name := new_level.name;
        NEW.level_name_jp := new_level.name_jp;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger para atualizar o level quando o experience for alterado
CREATE TRIGGER update_level_trigger
BEFORE UPDATE ON public.profiles
FOR EACH ROW
WHEN (OLD.experience IS DISTINCT FROM NEW.experience)
EXECUTE FUNCTION public.update_user_level();

-- Função para incrementar o xp
CREATE OR REPLACE FUNCTION public.increment_xp()
RETURNS void AS $$
BEGIN
    UPDATE public.profiles
    SET experience = experience + 10
    WHERE id = auth.uid();
END;
$$ LANGUAGE plpgsql;