-- supabase/migrations/20251110000001_add_ranks.sql

-- Adicionar a coluna login_count à tabela de perfis
ALTER TABLE public.profiles
ADD COLUMN login_count INT DEFAULT 0;

-- Criar a tabela de ranks
CREATE TABLE public.ranks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    name_jp TEXT NOT NULL,
    min_logins INT NOT NULL
);

-- Inserir os ranks
INSERT INTO public.ranks (name, name_jp, min_logins) VALUES
('Wakashu', '若衆', 0),
('Kyodai', '兄弟', 10),
('Shatei', '舎弟', 30),
('Chui', '中尉', 60),
('Komon', '顧問', 100),
('Shingiin', '審議委員', 150),
('Kaikei', '会計', 250),
('Wakagashira', '若頭', 500),
('Oyabun', '親分', 1000);




